### ISSUE TITLE
'select-searchable'

### ISSUE THREAD

**Issue by Shahidarain777** [eakoriakin/select-searchable-demo#1]
Uncaught (in promise): Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          title="Port"
          [(ngModel)]="port"
          [ERROR ->][items]="ports"
          itemValueField="id"
          itemTextField="name"
"): ng:///FormulasPageModule/FormulasPage.html@50:10
Can't bind to 'canSearch' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'canSearch' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          itemValueField="id"
          itemTextField="name"
          [ERROR ->][canSearch]="true"
          (onChange)="portChange($event)">
      </select-searchable>
"): ng:///FormulasPageModule/FormulasPage.html@53:10
'select-searchable' is not a known element:
1. If 'select-searchable' is an Angular component, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
   
    <ion-item>
      [ERROR ->]<select-searchable
          title="Port"
          [(ngModel)]="port"
"): ng:///FormulasPageModule/FormulasPage.html@47:6
Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          title="Port"
          [(ngModel)]="port"
          [ERROR ->][items]="ports"
          itemValueField="id"
          itemTextField="name"
"): ng:///FormulasPageModule/FormulasPage.html@50:10
Can't bind to 'canSearch' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'canSearch' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          itemValueField="id"
          itemTextField="name"
          [ERROR ->][canSearch]="true"
          (onChange)="portChange($event)">
      </select-searchable>
"): ng:///FormulasPageModule/FormulasPage.html@53:10
'select-searchable' is not a known element:
1. If 'select-searchable' is an Angular component, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
   
    <ion-item>
      [ERROR ->]<select-searchable
          title="Port"
          [(ngModel)]="port"
"): ng:///FormulasPageModule/FormulasPage.html@47:6

**Comment by Shahidarain777** [comment]
Please tell me how to resolve this issue 'select-searchable!!!

**Comment by eakoriakin** [comment]
Hi @Shahidarain777, I think you forgot to import `SelectSearchableModule` to your app.

Add `SelectSearchableModule` module to imports array of your app module.
```
    import { SelectSearchableModule } from '../components/select-searchable/select-searchable-module';

    @NgModule({
        imports: [ SelectSearchableModule ],
    })
    export class AppModule { }
```

Make sure a path to `select-searchable-module.ts` file is correct.

**Comment by Shahidarain777** [comment]
Hi @eakoriakin , i have done as u instructed here is my app.module.ts 


import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';



import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { SignUpPage } from '../pages/sign-up/sign-up';
import { TabsPage } from '../pages/tabs/tabs';
 import { IonicImageViewerModule } from 'ionic-img-viewer';
 import { SelectSearchableModule } from '../components/select-searchable/select-searchable-module';
@NgModule({
  declarations: [
    MyApp,
    HomePage,
    SignUpPage,
    TabsPage,
    
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    IonicImageViewerModule,
    SelectSearchableModule,
    

  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    SignUpPage,
    TabsPage,

  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

////////
can u  give me solution plz. Thank you

**Comment by eakoriakin** [comment]
@Shahidarain777 try adding in to `exports` sections as well

```
exports: [
    SelectSearchableModule
]
```

**Comment by Shahidarain777** [comment]
@eakoriakin bro i have add !!
exports: [
    SelectSearchableModule
]
app.module.ts but still getting the same error,  i need your more help to resolve this errorThank you for helping!

**Comment by eakoriakin** [comment]
@Shahidarain777  Do you have any other modules `@NgModule` in your app?

**Comment by Shahidarain777** [comment]
@eakoriakin No dear in my app there is only one @NgModule in app.module.ts file!!! i am working with ionic3

**Comment by eakoriakin** [comment]
@Shahidarain777 it's strange, have a look at the repository, it works there, maybe you missed something else

**Comment by luoboqian** [comment]
I met the same problem，i am working with ionic3

**Comment by luoboqian** [comment]
@Shahidarain777  Have you  solve the problem?

**Comment by eltoninacio** [comment]
Have you solve the problem?

**Comment by eakoriakin** [comment]
I cannot reproduce the issue. Can you share a demo, plunk or zip?

**Comment by mwvarela** [comment]
This error is when you use lazy loading. I have the same issue.

**Comment by jessicastorm1986** [comment]
Facing same error, as per docs i have imported  `import { SelectSearchableModule } from 'ionic-select-searchable';`  in my `dashboard.html` page, but error is still there, I am carefully imported in my app.module.ts

any help will be appreciated. Thanks

**Comment by eakoriakin** [comment]
Hey @jessicastorm1986, I can try to help you, if you create a repo with this error, so I could reproduce it
