### ISSUE TITLE
Label color

### ISSUE THREAD

**Issue by bassfan** [eakoriakin/select-searchable-demo#3]
Hi

I'm using your select in an app.  I have changed the sass variable $label-md-text-color to black as it seems the default label color is gray in android.  Everything gray would be fine but some of the labels are black and I'm not sure why (unrelated to this).  Anyways, if I set that variable to black, all is good...except my select-searchable input.  Can you make it abide by the same logic that normal labels use so it takes on the color of that variable?

Example:

![select-searchable](https://user-images.githubusercontent.com/24640360/35024881-955d95d6-fb07-11e7-8c13-08f7037b9865.PNG)

**Comment by eakoriakin** [comment]
Hello @bassfan, thanks for a feedback . It must be fixed now https://github.com/eakoriakin/select-searchable-demo/commit/f59246d3041fea7a25e26773a292ece360d1ea2d.
