### ISSUE TITLE
Using select-searchable on ion-toolbar

### ISSUE THREAD

**Issue by mwvarela** [eakoriakin/select-searchable-demo#4]
I'm trying to use the select-searchable inside the ion-toolbar, but the field is not showing correctly.

`<ion-header>
	<ion-toolbar color='primary'>
      <select-searchable
      title="Search"
      [items]="findArray"
      itemValueField="id"
      itemTextField="name"
      [canSearch]="true">
    </select-searchable>
		<ion-buttons end>
			<button ion-button icon-only (click)='scan()'>
				<ion-icon name="barcode"></ion-icon>
			</button>
		</ion-buttons>
	</ion-toolbar>
</ion-header>
![select-searchable](https://user-images.githubusercontent.com/5406160/35146832-66ed9adc-fcf3-11e7-9f61-0f32e34c891f.PNG)
`

**Comment by eakoriakin** [comment]
Yes, it does look quite weird 🙂 e.g. this gray color of the label on a blue background. However, is there any standard design for this case?

![select-searchable](https://image.prntscr.com/image/vBLSIgKVR_iiNbLhMkh-rg.png)

Ionic Select competent looks detached as well.

![select-searchable](https://image.prntscr.com/image/_qhlNKcVRp6DEwPHSpp4Pg.png)

I'd suggest that you add some custom styles to make it look the way you want. For example, changing label color:

```
.select-searchable-ios,
.select-searchable-md {
    .select-searchable-label {
        color: #ffffff;
    }
}
```

**Comment by mwvarela** [comment]
Ok, I will try.
