### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by Hemakirthi** [eakoriakin/select-searchable-demo#5]
I am getting below error please help me to sort this out

Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        itemValueField="code"
        itemTextField="name"
        [ERROR ->][items]="ports"
        [canSearch]="true"
        (onSearch)="searchPorts($event)"
"): ng:///Development/live/ULCARGO/src/pages/fschedule/fschedule.html@27:8

**Comment by eakoriakin** [comment]
Hi @Hemakirthi, I think you are using lazy loading, have a look at this [post](https://forum.ionicframework.com/t/ion-select-with-searchbar/89255/9?u=eakoriakin).

**Comment by Hemakirthi** [comment]
YES Eakoriakin 
while logging this issue i have tried suggestion made by mwvarela in ur previous closed issue
so it's worked and now app working in both android and ios without any issue 
and also i would like take this opportunity to thanks for the effort you made to developed this component because its awesome

**Comment by eakoriakin** [comment]
Thanks! It’s nice to hear that :)
